#!/bin/bash
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b cholesky -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b jacobi-1d -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b lu -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if y -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b ludcmp -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if n -u y -c n -d 32 -i 1
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if y -u y -c n -d 8 -i 2
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if y -u y -c n -d 8 -i 2
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if y -u y -c n -d 8 -i 2
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 32 -if n -u y -c n -d 8 -i 2
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 64 -if n -u y -c n -d 8 -i 2
./cache -o pre -s polybench -b trisolv -t small -m xor -um frequency -cm bdi -f 5000 -x 128 -if n -u y -c n -d 8 -i 2
